version: '2'
services:
  service:
    build: ./service
    volumes:
      - ./service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
  admin:
    build: ./admin
    volumes:
      - ./admin:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8000"
